import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react'

export default function Busca() {
    const [searchText, setSearchText] = useState('')
    const [resultsFromSearch, setResultsFromSearch] = useState([])

    const handleSearch = async () => {
        if (searchText != false) {
            const busca = await fetch(`http://localhost:3000/api/search?q=${searchText}`)
            const { results } = await busca.json()
            // console.log(results)
            setResultsFromSearch(results)
            document.getElementById('input').value = ''
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Busca
                </h1>

                <Link href={"/"}>Ir para o menu principal</Link>

                <input type="search" id='input' onChange={e => setSearchText(e.target.value)} />
                Termo de busca: {searchText}
                <button onClick={handleSearch}>Buscar filme</button>
                <hr />
                {resultsFromSearch &&
                    <div>
                        <ul style={{ listStyle: "none", margin: 0 }}>
                            {resultsFromSearch.map((item, index) => (
                                <li key={index} style={{ display: "inline-block", margin: "20px" }}>
                                    <a href={`/filmes/${item.id}`}>
                                        <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} style={{ width: '200px' }} />
                                        <p style={{ maxWidth: "190px" }}>{item.title}</p>
                                    </a>
                                </li>
                            )
                            )}
                        </ul>

                    </div>
                }
            </main>
        </div>
    )
}
