import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home({ results, name }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes em destaque
        </h1>
        <p>Meu nome é {name}</p>
        <Link href={"/busca"}>Ir para a busca</Link>
        <ul style={{ listStyle: "none", margin: '0px' }}>
          {results.map((filme, index) => (
            <li key={index} style={{ display: "inline-block", margin: "20px" }}>

              <Link href={`/filme/${filme.id}`}>
                <div>
                  <img src={`https://image.tmdb.org/t/p/original${filme.poster_path}`} style={{ width: '230px' }} />
                  <p style={{ margin: 0, maxWidth: "240px" }}>{filme.title}</p>
                </div>
              </Link>

            </li>
          ))}
        </ul>
      </main>

    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/trending')
  const pegarNome = await fetch('http://localhost:3000/api/hello')
  const { results } = await res.json()
  const { name } = await pegarNome.json()

  return {
    props: {
      results,
      name
    }
  }
}
